# Generated by Django 5.0.7 on 2024-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='author_name',
            field=models.CharField(default='Unknown Author', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='courses', to='courses.category'),
        ),
    ]
